# CI de Nível 01 - Disparo manual a partir de 1 clique
name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4

      - name: Instalando npm dependências
        run: npm install 

      - name: Testes E2E (end-to-end)
        run: npm run e2e

